#!/bin/bash
#PBS -N strong_64
#PBS -A insitu
#PBS -q prod
#PBS -l walltime=00:30:00
#PBS -l place=scatter
#PBS -k doe
#PBS -l select=16:system=polaris
#PBS -l filesystems=grand
#PBS -o strong_64.out
#PBS -e strong_64.err

source ~/.bashrc
source /lus/grand/projects/insitu/jkcenat/PyExner/machines/polaris.gpu
export MPICH_GPU_SUPPORT_ENABLED=1

cd $PBS_O_WORKDIR

MPI4JAX_USE_CUDA_MPI=1 mpiexec -n 64 --ppn 4 ../../set_affinity.sh mamba run -n pyexner python ../../run.py ./input.yaml
